spring:
    profiles:
        active: local
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}

jwt:
    header: Authorization
    secret: ${JWT_SECRET}

app:
    front-redirect-base: ${FRONTEND_URL}
    frontend-url: ${FRONTEND_URL}

cloud:
    aws:
        s3:
            enabled: false   # 로컬에서는 S3 Mock 사용 → AWS 자격증명 불필요
